--- #YAML:1.0
name:               Geo-Coder-YahooTaiwan
version:            0.02
abstract:           Yahoo! Taiwan Maps Geocoding API
author:
    - Yen-Ming Lee <leeym@leeym.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON::XS:        0
    LWP::UserAgent:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
